name: Build
on:
  push:
    tags:
      - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.18"
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go build
          for tag in "latest" "$GITHUB_REF_NAME"
          do
            ./dinker <<ELEPHANT
            {
              "dest": [
                "docker://ghcr.io/andrewbaxter/dinker:latest",
                "docker://ghcr.io/andrewbaxter/dinker:$GITHUB_REF_NAME",
              ],
              "dest_user": "$GITHUB_ACTOR",
              "dest_password": "$GITHUB_TOKEN",
              "arch": "amd64",
              "os": "linux",
              "files": [
                {
                  "source": "dinker",
                  "mode": "755"
                }
              ],
            }
            ELEPHANT
          done
